services:

  eureka-server:
    build:  ./eureka-server
    ports:
      - "9099:9099"
    
  api-gateway:
    build:  ./api-gateway
    ports: 
      - "8080:8080"
    depends_on:
      - eureka-server

  postgres:
    image: postgres
    restart:  always
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD:  postgres
      POSTGRES_DB:  kyc_db
    volumes: 
      - kyc-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"


  rabbitmq:
    image:  rabbitmq:4.1.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS:  guest
      RABBITMQ_DEFAULT_USER:  guest
    restart:  always

  kyc-service:
    build:  ./kyc-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - api-gateway
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://postgres:5432/kyc_db
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO:  update


  email-service:
    build: ./email-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - api-gateway
      - rabbitmq
    
  report-service:
    build:  ./kyc-backend-report
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://postgres:5432/kyc_db
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO:  update
    depends_on:
      - eureka-server
      - api-gateway
      - postgres

      
  kyc-report-frontend:
      build: ./kyc-report-front-end
      ports:
      - "4201:80"
      depends_on:
        - report-service
        
    

  kyc-frontend:
    build: KYC-customer-frontend
    ports:
    - "4200:80"
    depends_on:
      - kyc-service
      - email-service


volumes:
  kyc-data:
