spring:
  application:
    name: kyc-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url:  jdbc:postgresql://localhost:5432/kyc_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


server:
  port: 8081
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include:  health
  endpoint:
    health:
      show-details: always
  server:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:9099/eureka


rabbitmq:
  queue:
    name: email-queue
  routing:
    key:  email_key
  exchange: 
    name: email_exchange