spring:
  application:
    name: eureka-registry

server:
  port: 9099
  address: 0.0.0.0

  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

