name: Angular CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'kyc-report-front-end/**'
    branches: [ "main", "dev" ]
  pull_request:
    paths:
      - 'kyc-report-front-end/**'
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kyc-report-front-end

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Verify package-lock.json exists
        run: test -f package-lock.json || { echo "❌ package-lock.json missing"; exit 1; }

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: npm run build -- --configuration=production

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.STAN_USERNAME }}
          password: ${{ secrets.STAN_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kyc-report-front-end
          push: true
          tags: stanleyotieno/kyc-report-front-end:latest
