name: CD - API Gateway

on:
  workflow_dispatch:
  push:
    paths:
      - 'api-gateway/**'
    branches: [ "main", "dev"]
  pull_request:
    paths:
      - 'api-gateway/**'
    branches: [ "main", "dev"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api-gateway

    env:
      SPRING_PROFILES_ACTIVE: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: api-gateway/pom.xml

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CECIL_USERNAME }}
          password: ${{ secrets.CECIL_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: cecillwala/kyc-api-gateway:latest
