name: Build and test Spring-Boot project

on:
  push:
    paths:
      - 'kyc-backend-report/**'
    branches: [ "main"]
  pull_request:
    paths:
      - 'kyc-backend-report/**'
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kyc-backend-report

    permissions:
      contents: read
      security-events: write

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24 (LTS)
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.STAN_USERNAME }}
          password: ${{ secrets.STAN_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kyc-backend-report
          push: true
          tags: stanleyotieno/kyc-backend-report:latest
